### ISSUE TITLE
Base/nexus (enemy goal) assets

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#11]
We currently have a "goal" that enemy will converge to, and take damage when reached.
I'm not sure how to name it: base, nexus, HQ, town hall, whatever? It kind of depends on the theme and "story" (#2) so that we know what are those enemies actually trying to attack :D

At any rate, this base will need some graphics too.

**Comment by ObaniGemini** [comment]
Nexus is more "cool" IMO :p

**Comment by akien-mga** [comment]
Yeah, it kinds of depends on the base "scenario" we're going for, to be discussed in #2 I guess.

**Comment by alketii** [comment]
Or it can be "The Tree of Life" (something like Yggdrasil) which is the very center of the universe, and the player is the guardian of it.

**Comment by akien-mga** [comment]
@alketii addressed part of the issue with 936303d. As we haven't decided if it's a "final" base, I'll keep this issue open anyway.

**Comment by bojidar-bg** [comment]
Should we keep it open after @fry- 's work in 563034c71cd4df417cc916fe9dc9f77094ce85d9 and 32671a19b96bf8aa9bf17dd2232d6e05491ab6bf ?

**Comment by akien-mga** [comment]
It's fixed indeed.
