### ISSUE TITLE
Placing several towers without having to select them each time

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#13]
In my latest commit that fixed #12 (b5cc738), I made it so that once you have placed your tower, the cursor goes back to normal mode (i.e. not tower placement mode).

We might want to make it stay in tower placement mode so that you can place several towers at once. That's quite easy technically but raises one small question: how to handle the budget modification at each click?

Right now the transaction money is removed as soon as you click the button; that's fine if you place one tower, but if you place more than one, then you should get some money removed at each click, and then get the last transaction back once you cancel the tower placement mode. That would be a bit confusing IMO.

I guess a better solution would be to remove the money only when actually placing a tower, WDYT? (long issue for a very simple question, but well :p)

**Comment by bojidar-bg** [comment]
@akien-mga ~ IMO, money should be removed at the moment in which the player places the tower, not when he clicks the button. Might look into it later.

**Comment by alketii** [comment]
Yes, I agree, charge per placement instead of click in the button, thats more practical.
