### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#14]
Now that we decided on node naming conventions (#9), we also need some guidelines for the code style.

As I'm a selfish dude, I propose to use the conventions I used in e.g. enemy.gd: https://github.com/KOBUGE-Games/project-kumquat/blob/49dc219/scripts/enemy.gd (or actually also used in @bojidar-bg's level.gd: https://github.com/KOBUGE-Games/project-kumquat/blob/a3d7f76/scripts/level.gd)

Proposal:

_Code structure_
- If applicable, inner classes definitions on top (as in level.gd)
- Variables section afterwards
  - consts are put on top, names are SNAKE_CASE
  - normal variables are put just after consts, names are snake_case
    - variables are more or less sorted by "usage" when possible
    - comments about variables are put inline, two spaces after the declaration (that's open to discussion, I just started using it ;))
- Methods section afterwards
  - callbacks first (_ready, _init, _input, etc.), in whichever order we find most natural (I'd say order of usages, i.e. _init, _enter_tree (or is it processed before _init?), _ready, and so on)
  - custom functions come next (helper functions, do_stuff(), etc.)
  - signals at the end (_on_button_pony_pressed, etc.)

_Code style_
- comments start with an uppercase letter, don't end with a dot (unless there are several sentences) --> PEP8 style
- operators:
  - spaces both on the left and right of =, ==, <, <=, +=, *=, etc.
  - spaces both on the left and right of +, - and % (or would you prefer no spaces for % ?)
  - no spaces around \* and /
- parentheses around conditionals (`if (true):`)

I might be forgetting a couple things, but you'll complete. Once we agree on this, we should probably make a guideline and put it in someplace where we can use it as a reference in all projects.

**Comment by bojidar-bg** [comment]
Ok, my opinions on the subject (e.g. things I dislike in that proposal :stuck_out_tongue: )
- Comments after variables/constants should be inline and with a _single_ space between them and the variable name. (`var name # Explanation`) _Edit: OK_
- Conditionals should have _no_ parenthesis around them. (`if condition`) _Edit: OK_
- Section beginning comments should have only two hashes (`#`), and not 3, before and after them (or if you would like it better, only before them) _Edit: OK_

Stuff I would like to add (e.g. forgotten)
- Operators:
  - Conditional operators should be written in words and surrounded by spaces (`condition or (condition and condition)`) _Edit: OK_
  - If there is some ambiguity in the order of conditional operators, like when `or`-s and `and`-s are mixed, use parentheses to explain what you mean (`condition or (condition and condition)`, `(condition or condition) and condition` _Edit: OK_
  - Parentheses should have no spaces, except if they are required by an operator. _Edit: OK_
  - Square brackets should have no spaces, except if they are nested (`array[6]`, but `array_a[ array_b[5] + 1 ]`) (Please comment :wink: )

**Comment by akien-mga** [comment]
> Conditionals should have no parenthesis around them. (`if condition`)

After discussion on IRC, we agree on @bojidar-bg's proposal by two votes against one :)

> Square brackets should have no spaces, except if they are nested (`array[6]`, but `array_a[ array_b[5] + 1 ]`) (Please comment :wink: )

For array indexes, I'd tend to go with no spaces, even when nested.
For array definitions however, I'm not completely against using spaces for complex types, e.g.:
`var list = [1, 2, 3]` but `var list = [ Vector2(1, 2), Vector2(3, 4), Vector2(5, 6) ]`.
Or all without spaces if we don't want to make the guidelines too complicated: `var list = [Vector2(1, 2), Vector2(3, 4), Vector2(5, 6)]`

**Comment by akien-mga** [comment]
Some additions:
- Functions and constructor arguments are separated by a comma + a space, i.e. `Vector3(1, 2, 3)` and not `Vector3(1,2,3)`
- Indentation with tabs as it's more or less imposed by Godot's editor.
- Indentation is kept even on empty lines so that function blocks are actually blocks :), i.e.:

```
func _ready():
<TAB>stuff
<TAB>
<TAB>pass
```

instead of:

```
func _ready():
<TAB>stuff

<TAB>pass
```
- Files end with one (1) empty new line
- Multiple conditionals are split when too long, ideally before a "and" or "or". The split lines are double-indented to make sure they are not mistaken for the statements of the if block, i.e.:

```
if first_very_long_condition_that_takes_already_more_than_half_of_the_screen_size
        and second_condition:
    pass
```

**Comment by bojidar-bg** [comment]
Current working draft: https://public.etherpad-mozilla.org/p/WFYfzKFNHm

**Comment by akien-mga** [comment]
The current draft is quite good IMO, I just put some comments on the pad.
Should we make a KOBUGE-Games/doc repo to put this markdown file, and maybe other stuff that we might need later on?

Or should we make it a KOBUGE-Games/shared or KOBUGE-Games/resources repo, where we could also in time place code and game templates, or stuff like that?

**Comment by akien-mga** [comment]
> Should we make a KOBUGE-Games/doc repo to put this markdown file, and maybe other stuff that we might need later on?
> 
> Or should we make it a KOBUGE-Games/shared or KOBUGE-Games/resources repo, where we could also in time place code and game templates, or stuff like that?

Could also be KOBUGE-Games/main or similar, with a README.md that lists all our repos with some more explanations and order as the default GH view which sorts by modification date.

**Comment by bojidar-bg** [comment]
@akien-mga ~ A `KOBUGE-Games/resources` sounds good, and it might be made from the current logo repository.

**Comment by akien-mga** [comment]
> A KOBUGE-Games/resources sounds good, and it might be made from the current logo repository.

+1

@bojidar-bg I let you handle that? Rename the logo repo, move files to a logo subfolder maybe, and add the guidelines in a Markdown file?

**Comment by akien-mga** [comment]
The style guide is now official: https://github.com/KOBUGE-Games/resources/blob/master/STYLE-GUIDE.md

There are still a couple changes that we might want to make in the code to follow, but we're not far from being compliant already, so I'll close this issue.
