### ISSUE TITLE
How to handle the various tower types architecture-wise

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#16]
We need to decide how we want to handle the various tower types at the architecture level. What I mean by that is whether we should use one separate scene file for each tower type, share some parts with subscenes, use scene inheritance, etc.
1. One scene file per tower type: all those scenes would like using the tower.gd to share the basic mechanism. It's likely the easiest solution, but means that changes done in one scene will have to be done again in all scenes if they are relevant for all tower types; we won't have many tower types though so it's maybe not a big deal.
2. One scene file per tower type, all instancing a common subscene for the parts that are common to all towers (home-made scene inheritance).
3. Only one tower scene, and differentiate all tower types using export member vars. The problem of this approach might be that we'll need to change many parameters in _ready() based on the export vars (spritesheet, etc.), and it might be problematic if we want to use different animations or sounds.
4. One tower scene, and use of the new scene inheritance mechanism. I have no idea how this works, but that might be worth looking into (or maybe just for enemies).

Are there other possibilities? WDYT about the ones above?
I guess 1. or 2. are likely the simplest solutions if we have only ~4 tower types.

**Comment by bojidar-bg** [comment]
I guess with 2 or 4 and script inheritance. That means a base `tower.gd` script, and (when needed) `tower_laser.gd`, etc., that would implement specific animations, special abilities, and so on.

**Comment by bojidar-bg** [comment]
Close?

**Comment by akien-mga** [comment]
Yep, we'll go with scene inheritance for now, it looks interesting.
