### ISSUE TITLE
Better GUI / HUD layout

### ISSUE THREAD

**Issue by fry-** [KOBUGE-Games/project-kumquat#20]
I would like to see some more buttons on the HUD, so you can build Tier 2 / 3 Towers right away.
- Left: Initial HUD state, where you start all with Tier 1 towers. you can upgrade them per tower-type, and if you did that, you can upgrade the single towers of that type on the map too (gets unlocked by upgrading in general)
- Right: shows a more advanced state in the game. The player has upgraded some of the towers. Also, he has got some enemies entering his goal, so the "next wave" button is disabled and he has to disable towers / set towers to spawning points before he can go with the "next wave".

Let me know your opinion, criticism, ideas, ... :grinning: 

![new_gui](https://cloud.githubusercontent.com/assets/10758005/12378575/70d2dafa-bd42-11e5-8d6d-e7dfda4b716f.png)

**Comment by akien-mga** [comment]
+1 Awesome :-D

**Comment by est31** [comment]
:+1:

**Comment by bojidar-bg** [comment]
:+1:, but please change _that_ yellow color... :smile:

**Comment by fry-** [comment]
@bojidar-bg sure, its just a sketch to show my idea :smile: Will need proper art for that ofc :stuck_out_tongue_closed_eyes:

**Comment by ObaniGemini** [comment]
:+1: This is a very good idea. I think I can see the RTS inspiration for researches ^^

**Comment by fry-** [comment]
Oh yeah what I kinda didn't made clear is that pressing on the "UP" to tech from tier 1 -> 2 just unlocks tier 2, but doesn't changes any tower on the map.

Also, **we might need a 4th (smaller) button column besides the tier 1 2 3 buttons that makes the "upgrade as much towers as possible (with current money) of this type on the map to the currently highest tier (chosen randomly or with some logic)"**

@ObaniGemini hehe yeah I guess I got subtly inspired by RTS without even noticing :smile: I see the similarities too now.

**Comment by bojidar-bg** [comment]
@fry- @akien-mga Should we remove the "discussion" tag?

**Comment by akien-mga** [comment]
It's mostly fixed with my latest changes, but I'll keep this open for now to check :) I also need a better upgrade icon ;)

**Comment by akien-mga** [comment]
Fixed, now superseded by #29.
