### ISSUE TITLE
Building towers can't be choosen when not enough money

### ISSUE THREAD

**Issue by fry-** [KOBUGE-Games/project-kumquat#22]
When you have insufficent money, you can not click on the tower buttons for entering build-mode.

I think this is quite problematic, because it slows things down. You are not able to properly prepare for building / placing your next tower as soon as the money is there. So when you know that you want to place Tower ABC at position X/Y the next, you cannot preselect this tower and hover over X/Y to click in the instance you get the money. Instead, you have to go to the tower buttons first, wait for the money, click it, go to X/Y and click again.

Since you cannot buy a tower if you have not enough money anyways, I see no point in disabling the buttons.

Instead, some visible effect on the buttons that can't be build currently would be fine, but without changing the buttons function itself. Maybe just make the buttons' tower image grayed out or so.

**Comment by bojidar-bg** [comment]
:+1: I tried to fix this once, but as I didn't want to waste too much time (had just made big changes on `hud.gd`), I stopped quickly...

**Comment by bojidar-bg** [comment]
Fixed in bb5af5f9c5fe617fe7c85bd99f3e6d7ce481ef13
