### ISSUE TITLE
Mouse symbols for building / upgrade don't refresh when money changes

### ISSUE THREAD

**Issue by fry-** [KOBUGE-Games/project-kumquat#23]
When you are about to place a tower or an upgrade, and you currently have not enough money for that, the symbol at the mouse for that is of course red (which is fine). But if you don't move the mouse and the money increases to a point where **you can build / upgrade the tower, the symbol simply stays red.**
The game logic is fine, because you can actually build / upgrade in that moment, it's just the images that don't refresh.

Reproduction steps:
1. Build as much towers as you can.
2. Keep the mouse in tower building mode, and place it somewhere where you can build a tower (but you are out of money).
3. **DON'T MOVE THE MOUSE FROM NOW ON**.
4. Wait for enemies to die to the current towers, so your money increases again to a level where you can build the tower.
5. Look at the symbol: it's still red. Press the mouse: tower gets placed and money goes away (like expected, this works fine).

**Comment by bojidar-bg** [comment]
Fixed in bb5af5f9c5fe617fe7c85bd99f3e6d7ce481ef13, by changing the way symbol-changing works.
