### ISSUE TITLE
Upgrade button costs as much as buying tier2 or tier3 from scratch

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#25]
The upgrade button should only charge the different between the existing tower and the tower of tier+1.
Should be relatively simple to do but I haven't understood yet how upgrading towers work :D

**Comment by akien-mga** [comment]
Fixed by fed0955.

**Comment by bojidar-bg** [comment]
Heh, my idea was that tier price for tier > 1 is equal to the price for upgrade from tier - 1...

**Comment by akien-mga** [comment]
> Heh, my idea was that tier price for tier > 1 is equal to the price for upgrade from tier - 1...

But that's not what we want, since there is now a way to place tier2 directly without paying tier1 first. So we can't have the tier2 button cost the price of tier2, but upgrading a tier1 costing the price of tier1 (existing) and tier2 (upgrade) :)

**Comment by ObaniGemini** [comment]
I think upgrade button should cost a little bit more than tierX. But that's just optimization and we don't need it now ^^
