### ISSUE TITLE
Version of godot to use with kobuge games

### ISSUE THREAD

**Issue by openelearning** [KOBUGE-Games/project-kumquat#37]
Hello,

I just discovered godot and this project of making open source games with godot. That's really cool, thanks to all the contributors. Someone know how I can know which version of Godot I have to use for each projects of Kobuge games ? (ie : I have seen that for an other open source game tanks made with Godot they told to use the 2.1.4 version of godot). For Kobuge games, It's only the version 2 of Godot, the latest stable (the 2.1.5 ) ?
Thanks

**Comment by bojidar-bg** [comment]
Different games use different version. Most of them should work in 2.1.5, though a few are 2.2 only or 3.x.x only.

**Comment by openelearning** [comment]
Thanks a lot for your reply. Do you know how I can know for each game where I can find this information  ? (ie. I can see in a file, I have to ask in github for each game...).
Best regards

**Comment by bojidar-bg** [comment]
It is simple: run the game with each of the mentioned versions, and pick the least one in which it works :smiley: 

More seriously: If there is an `engine.cfg` file, it is for 2.x, if there is a `project.godot` file, it is for 3.x.

**Comment by openelearning** [comment]
Ok perfect : 
project.godot the last stable of 3.X
engine.cfg the last stable of 2.X :  2.1.5 > if KO 2.2
Thanks a lot !

**Comment by akien-mga** [comment]
It would be worth making it clear in the README of each repo.

**Comment by openelearning** [comment]
Good idea, this is how Tanks of freedom did it : https://github.com/w84death/Tanks-of-Freedom
