### ISSUE TITLE
Initial tower behaviour

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#7]
They should fire at a regular interval on an enemy in range.

I think that typically, the tower should start by locating the closest enemy in range, and the lock onto it: it will fire at it as long as it's still in range and not dead, even if it's not the closest enemy anymore. Once it leaves the tower range, we go back to searching for the nearest enemy and lock onto it.

**Comment by bojidar-bg** [comment]
Done in 3c7756a.
