### ISSUE TITLE
Node naming conventions

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/project-kumquat#9]
A useless nerdy issue from your favourite OCD guy :D

We currently use different conventions for the naming of nodes, it would be cool to homogenize it (especially so that the get_node("/root/blablabla") calls are not so impacted by case-sensitiveness.

So far we have:
- CamelCase: that's what Godot uses by default (e.g. "SamplePlayer" or "AnimatedSprite"), so that's what I'm using too personally. So we have "Enemy", "Tower", "Level", etc.
- camelCase: in the HUD scene we have "btnTower"
- lower case with underscores: in level scene "tilemap_grass", "tilemap_tower", in HUD scene, "coin_icon", "next_wave", "tower_name"
- random: in HUD scene, "Tower_desc" ;)

I'd propose to use CamelCase for all node names, and lower case with underscores for scene filenames (i.e. only scenes/btnTower.xscn would have to be renamed to scenes/btn_tower.xscn right now).

If that's fine with you I'll do the corresponding changes asap.

**Comment by bojidar-bg** [comment]
I'm for snake case (e.g. underscores with small letters)

**Comment by akien-mga** [comment]
> I'm for snake case (e.g. underscores with small letters)

Grrr... that means we'd have to rename default node names like "Sprite" or "Label" to appease my OCD :P
But I'm not against snake case either :)

**Comment by alketii** [comment]
For_godot_I_prefer_snake_case_as_long_as_they_may_be

**Comment by akien-mga** [comment]
> For_godot_i_prefer_snake_case_as_long_as_they_may_be

You mean:
**f**or_godot_i_prefer_snake_case_as_long_as_they_may_be

:)

**Comment by akien-mga** [comment]
Let's go with snake_case then, so all lowercase (including first letter) with words separated by underscores. To make me happy, it also means that when adding nodes like Sprite of AnimatedSprite, if they don't need a specific name, they should be renamed to "sprite" and "animated_sprite". You asked for it :P

**Comment by alketii** [comment]
Camel_Snake :dancer:

**Comment by akien-mga** [comment]
I'll handle snake_casing all nodes then.
